server:
   port: 9200
  
spring:
   application:
      name: thmarket-zuul-server
#   zipkin:
#       base-url: http://127.0.0.1:9411/
#       locator:
#          discovery:
#             enabled: true
#       sender:
#          type: web
#       sleuth:
#          sampler:
#             percentage: 1.0
#             probability: 1
#          web:
#             skipPattern: (^cleanup.*|.+favicon.*)

eureka:
   client:
      service-url:
         defaultZone: http://localhost:9100/eureka/
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
    
zuul:
   routes:
      thmarket-user-service:
         path: /api/**
         url: http://localhost:9000/
#         service-id: thmarket-user-service  #(此行不起作用)
