server:
   port: 9300
  
spring:
   application:
      name: thmarket-gateway-server
   cloud:
      gateway:
         discovery:
            locator:
               enabled: false
               lowerCaseServiceId: true
         routes:
            - id: thmarket-user-service
              uri: http://localhost:9000/
              predicates:
                 - Path=/api/**
              filters:
                 - StripPrefix=1
